### ISSUE TITLE
libtool compiled failed

### ISSUE THREAD

**Issue by Vagant1** [ProgrammingRainbow/Beginners-Guide-to-SDL2-in-Gforth#2]
Hi,
I would really like to dive into your tutorial and learn from it but I am having issues when I try to run the main example file with gforth:

> gforth main.fs
sh: line 1: --silent: command not found

in file included from *OS command line*:-1
in file included from main.fs:1
in file included from SDL2/SDL.fs:2
SDL2/c-helper.fs:22: libtool compile failed
>>>end-c-library<<<
Backtrace:
$7FA0FCA04988 throw 
$7FA0FCA40780 c(abort") 
$7FA0FCA41380 compile-wrapper-function1

**Comment by ProgrammingRainbow** [comment]
do you have libtool installed? Lets start from the beginning. Do you have SDL and it's modules installed with there headers. Do you have a C build environment. I'm not sure exactly what is needed i just have the standard base-devel meta package installed. SDL2 is C forth is making use of C through those SDL2 Forth bindings. Also make sure your using 0.73 not 0.79 version of GForth.

**Comment by Vagant1** [comment]
I have libtool installed as well as the whole C build environment. I did some digging and this error against gforth has been reported i.e. here: https://stackoverflow.com/questions/49602892/error-with-gforth-libtool-compile-failed
The proposed solution was to add libtool-bin package. I am on opensuse linux and can't see it so will do some more digging. I have gforth 0.7.3. I can see few people raising issues with similar issues with gforth and libtool.

**Comment by ProgrammingRainbow** [comment]
That libtool-bin, is just libtool. Each Linux distro names there packages differently, and many separate out the binary, library, and headers. I'm on Arch BTW and they don't. Forth goes and compiles all the C bindings in Forth to C libraries the first time you run it. This is where you are having an issue. Something is going wrong with the compiling of the C part. The simplest way i can think of to track this issue down, is to just have you compile a SDL2 C project. Just to see if it compiles, that will let us know a little better what may be missing, or if it's actually nothing to do with the C SDL2 stuff, and if it's Gforth. So I propose just git clone my SDL2 Yellow Snow project, and run make. If it compiles, your C environment is good. But if it doesn't it should give us a better output on what is going wrong. 
```
git clone https://github.com/ProgrammingRainbow/Yellow-Snow-C-SDL2
cd Yellow-Snow-SDL2
make
```

This project requires SDL2 to be installed and a C build system. Basically exactly what the Gforth will need but not the Gforth part.

Any errors compiling this will be much more helpful.

**Comment by Vagant1** [comment]
It has compiled and runs flawlessly.

**Comment by ProgrammingRainbow** [comment]
What is the entire error that Gforth gives you? Does it say it couldn't find libtool or is it just an error in libtool?

**Comment by Vagant1** [comment]
gforth main.fs

sh: line 1: --silent: command not found

in file included from *OS command line*:-1
in file included from main.fs:1
in file included from SDL2/SDL.fs:2
SDL2/c-helper.fs:22: libtool compile failed
 >>>end-c-library<<<
Backtrace:
$7F7DD8C04988 throw 
$7F7DD8C40780 c(abort") 
$7F7DD8C41380 compile-wrapper-function1 


Ignore formatting  please.

**Comment by Vagant1** [comment]
![image](https://github.com/user-attachments/assets/df55b436-d2de-4434-9d00-dfe89ef7ed2c)

**Comment by Vagant1** [comment]
When I am in gforth and I type in 'end-c-library' I am getting immediately the same error

**Comment by ProgrammingRainbow** [comment]
Yeah it's failing when it's working on the C bindings.
```
\ ----===< prefix >===-----
c-library c_helper

\c #include <stddef.h>
\c int sizeof_char() { return sizeof(char); }
\c int sizeof_short() { return sizeof(short); }
\c int sizeof_size_t() { return sizeof(size_t); }
\c int sizeof_int() { return sizeof(int); }
\c int sizeof_float() { return sizeof(float); }
\c int sizeof_double() { return sizeof(double); }
\c int sizeof_pointer() { return sizeof(void *); }

c-function sizeof_char      sizeof_char     -- n ( -- size )
c-function sizeof_short     sizeof_short    -- n ( -- size )
c-function sizeof_size_t    sizeof_size_t   -- n ( -- size )
c-function sizeof_int       sizeof_int      -- n ( -- size )
c-function sizeof_float     sizeof_float    -- n ( -- size )
c-function sizeof_double    sizeof_double   -- n ( -- size )
c-function sizeof_pointer   sizeof_pointer  -- n ( -- size )

\ ----===< postfix >===-----
end-c-library
```

this is saying to compile a c function
```
#include <stddef.h>
int sizeof_char() {
    return sizeof(char);
}
```
And in forth says i want a word sizeof_char that is the c function sizeof_char so i can get the size of char in forth. Because size of char is not set in stone.
```
\c #include <stddef.h>
\c int sizeof_char() { return sizeof(char); }

c-function sizeof_char      sizeof_char     -- n ( -- size )
```

**Comment by ProgrammingRainbow** [comment]
I was trying to figure out how to get Gforth to be verbose in it's libtool or gcc output but i have not been able to find anything helpful.

**Comment by ProgrammingRainbow** [comment]
For fun you can try to compile that code as C code and use libtool and see if it errors.

test.c
```
#include <stddef.h>
#include <stdio.h>

int sizeof_char() { return sizeof(char); }
int sizeof_short() { return sizeof(short); }
int sizeof_size_t() { return sizeof(size_t); }
int sizeof_int() { return sizeof(int); }
int sizeof_float() { return sizeof(float); }
int sizeof_double() { return sizeof(double); }
int sizeof_pointer() { return sizeof(void *); }
int main() {
    printf("sizeof_char %u\n", sizeof_char());
    printf("sizeof_short %u\n", sizeof_short());
    printf("sizeof_size_t %u\n", sizeof_size_t());
    printf("sizeof_int %u\n", sizeof_int());
    printf("sizeof_float %u\n", sizeof_float());
    printf("sizeof_double %u\n", sizeof_double());
    printf("sizeof_pointer %u\n", sizeof_pointer());
}
```
then use libtool to compile and link it like this.
```
libtool --mode=link gcc -o test test.c

```

**Comment by Vagant1** [comment]
![image](https://github.com/user-attachments/assets/e57eb108-f681-47bf-bda7-d7815c4d7415)

**Comment by Vagant1** [comment]
It worked - no issues here

**Comment by ProgrammingRainbow** [comment]
So it's some deal with gForth but i couldn't find any way of getting valuable information out of gforth. There is --debug and --diag but they don't tell you anything about what happens in libtool or gcc.

**Comment by Vagant1** [comment]
Running out of ideas here...

**Comment by ProgrammingRainbow** [comment]
Yeah I have no ideas. Sadly we don't have information to work with. You
will have to poke one of the gforth guys and ask how to get info on what is
failing. Since its just not saying what's going wrong with libtool or gcc.

**Comment by ProgrammingRainbow** [comment]
There is a Facebook page for forth, someone may know more about gforth. There is also the person who asked about the licence, he may know more. Or go the ultra fun bug report to the gforth devs. I already tried Google as you did, and several LLMs but didn't find anything helpful.

**Comment by Vagant1** [comment]
Tried to recompile again gforth from source and when I simply type this I have following error:

![image](https://github.com/user-attachments/assets/73ec28d2-6719-4641-9faa-c1223f5d87c1)

But when I try to compile main one I have a bit different error:

![image](https://github.com/user-attachments/assets/c7dc5dbd-b7ae-424f-8d2e-2eeb3304144d)

**Comment by ProgrammingRainbow** [comment]
How did you compile it to get that output? It's saying the sizeof_char() function has not been defined but it is defined right above. That's the whole point of that helper is to get the sizes of the C types.

**Comment by Vagant1** [comment]
Just downloaded the latest 0.7.3 gforth source in tar file, run ./configure and make.
Then in gforth I just typed those three lines.

**Comment by ProgrammingRainbow** [comment]
Oh i see your manually typing in those. But that wont work because gforth needs to have compiled those C libraries.

**Comment by ProgrammingRainbow** [comment]
These binding libraries get compiled to ~/.gforth directly the first time you run the code. After that it just used them I could just give you my one. Though you are on a different os them me so it may or may not work.

**Comment by Vagant1** [comment]
Issue solved. I downloaded latest gforth from github and compliled - version 0.7.9 and ... it worked!

![image](https://github.com/user-attachments/assets/e638ef8a-af06-45dd-b051-2c93de967404)

**Comment by ProgrammingRainbow** [comment]
Oh that is good. I was just about to ask you if you had this file installed

/usr/include/gforth/0.7.3/libcc.h

maybe the suse package didn't have the header file for libcc that seems to be needed for gforth to build it's c bindings.

**Comment by Vagant1** [comment]
Thanks for all your help! Really appreciate!

**Comment by ProgrammingRainbow** [comment]
well if you make a program please let me see it when your done.
